name: Create XCFramework

# Create XCFramework when a new tag is pushed
on:
  push:
    tags:

jobs:
  create_xcframework:
    name: Create XCFramework
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v2

      - name: Create XCFramework
        uses: mohamed-3amer/spm-create-xcframework@v1.0.0
